---
     title: "Teaching"
     output:
       html_document:
         theme: sandstone
         css: style.css
         toc: false
---
\  

# Teaching Experience

2019 Spring  
**Botany: A Human Concern, BOT-101.**  Instructor of record.  4 credits.  144 students.  6 weekly in-person hours.  Responsible for design and delivery of lecture and lab course.  Introductory botany for non-majors, emphasizing the role of plants in the environment, agriculture and society. Includes molecular approaches to the study of plant function and genetic engineering.  
\  

2017 Spring  
**Plant Systematics, BOT-321.**  GTA.  4 credits.  60 students.  6 weekly in-person hours.  Responsible for field and lab portion of lecture/lab course.  Vascular plant botany, classification, diversity, and evolutionary relationships.  Labs emphasize field collection and identification of ferns, gymnosperms, and flowering plants in the regional flora.  Field trips with focus on plant identification and ecological interactions with environment and resources.  
\  

2013 Spring / 2012 Fall / 2012 Spring / 2011 Fall  
**Principles of Modern Biology, BIO-197.** GTA.  4 credits.  70 students.  12 weekly in-person hours.   Responsible for field and lab portion of lecture/lab course.  Whole-organism biology in an evolutionary context; biodiversity, structure, function and reproduction of organisms.  Evolutionary and ecological pattern and process.  For majors and advanced study in biology.  
\  

2012 Spring  
**Advanced Topics: Ecology \& Evolution Graduate Seminar, BIO-796.** 2 credits.  4 students.  2 weekly in-person hours.  Seminar course.  Co-developed with Dr. L.R. Walker.  Focus on synthesizing modern perspectives in disturbance ecology, landscape and ecosystem dynamics, biogeography, evolutionary and historical processes driving plant biodiversity.  For advanced graduate degree seekers in ecology and evolution.  
\  
